/**
 * Emits the Go and frontend copies of the notification template table.
 *
 * packages/shared/src/notification-templates.ts is the single source of truth.
 * notification-service is Go and cannot import it, and apps/web loads its
 * strings from locale JSON, so both need a copy. Hand-copying thirty templates
 * in two languages across two languages of implementation is the arrangement
 * CLAUDE.md already records drifting for the fee table, the completeness table,
 * and the per-service osv-scanner.toml files, so it is generated and CI fails
 * when the checked-in output moves.
 *
 * The web JSON nests under a literal 'notification' key so a stored
 * template_key of 'notification.milestone_submitted' resolves as-is inside the
 * 'notification' namespace. Flattening it would make the database column and
 * the i18next lookup path two different strings that have to be kept in step.
 *
 * Usage: bun run apps/notification-service/scripts/generate-notification-templates.ts
 *        bun run apps/notification-service/scripts/generate-notification-templates.ts --check
 */
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  NOTIFICATION_TEMPLATES,
  type NotificationLocale,
} from '../../../packages/shared/src/notification-templates'

const GENERATOR = 'apps/notification-service/scripts/generate-notification-templates.ts'
const SOURCE = 'packages/shared/src/notification-templates.ts'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..')
const goPath = join(root, 'apps', 'notification-service', 'internal', 'notify', 'templates_gen.go')
const localePath = (lng: NotificationLocale) =>
  join(root, 'apps', 'web', 'src', 'locales', lng, 'notification.json')

const keys = Object.keys(NOTIFICATION_TEMPLATES).sort() as (keyof typeof NOTIFICATION_TEMPLATES)[]

function goString(value: string): string {
  return JSON.stringify(value)
}

function goFile(): string {
  const rows = keys
    .map((key) => {
      const entry = NOTIFICATION_TEMPLATES[key]
      const locales = (['id', 'en'] as const)
        .map(
          (lng) =>
            `\t\t\t${goString(lng)}: {Title: ${goString(entry[lng].title)}, Message: ${goString(entry[lng].message)}},`,
        )
        .join('\n')
      return `\t${goString(key)}: {\n\t\tByLocale: map[string]Template{\n${locales}\n\t\t},\n\t},`
    })
    .join('\n')

  return `// Code generated by ${GENERATOR}. DO NOT EDIT.
// Source of truth: ${SOURCE}

package notify

// Template is one notification's wording in one language.
type Template struct {
	Title   string
	Message string
}

// Entry holds every language a template ships in, keyed by the value stored in
// user.locale.
type Entry struct {
	ByLocale map[string]Template
}

// Templates is the catalog. Keys are the values written to
// notifications.template_key and read back by the frontend.
var Templates = map[string]Entry{
${rows}
}
`
}

function localeFile(lng: NotificationLocale): string {
  const tree: Record<string, { title: string; message: string }> = {}
  for (const key of keys) {
    // Keys already carry the 'notification.' prefix; the namespace file nests
    // it literally so the stored key is the lookup path.
    tree[key.slice('notification.'.length)] = { ...NOTIFICATION_TEMPLATES[key][lng] }
  }
  return `${JSON.stringify({ notification: tree }, null, 2)}\n`
}

const outputs: Record<string, string> = {
  [goPath]: goFile(),
  [localePath('id')]: localeFile('id'),
  [localePath('en')]: localeFile('en'),
}

/*
--check re-renders in memory and byte-compares rather than asking git, for the
same reason generate-pricing.ts does: generated files are tracked on some
branches and untracked on others, and `git diff --exit-code` never sees the
untracked case.
*/
if (process.argv.includes('--check')) {
  const stale: string[] = []
  for (const [path, want] of Object.entries(outputs)) {
    const got = await readFile(path, 'utf8').catch(() => '')
    if (got !== want) stale.push(path.slice(root.length + 1))
  }
  if (stale.length > 0) {
    console.error(`${SOURCE} has changed but ${stale.join(', ')} was not regenerated.`)
    console.error(`Run: bun run ${GENERATOR}`)
    process.exit(1)
  }
  console.log(`${Object.keys(outputs).length} generated files match ${SOURCE}`)
} else {
  for (const [path, contents] of Object.entries(outputs)) {
    await writeFile(path, contents, 'utf8')
  }
  console.log(`wrote ${Object.keys(outputs).length} files from ${keys.length} templates`)
}
