import { Document, Page, StyleSheet, Text, View } from '@react-pdf/renderer'
import type React from 'react'

export type InvoiceData = {
  invoiceNumber: string
  issuedAt: string // ISO date
  projectTitle: string
  milestoneTitle: string
  milestoneDescription: string
  owner: { name: string; email: string }
  talent: { name: string; email: string }
  amount: number
  paymentMethod: string
  paymentRef: string
  platformFee?: number // present in admin copy only
  isAdminCopy: boolean
}

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: 'Helvetica' },
  header: { fontSize: 18, marginBottom: 20, color: '#152e34', fontWeight: 'bold' },
  section: { marginBottom: 12 },
  row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  label: { color: '#5e677d' },
  value: { color: '#152e34' },
  table: { borderTop: 1, borderColor: '#3b526a', marginTop: 12, paddingTop: 8 },
  total: { fontSize: 14, fontWeight: 'bold', color: '#152e34', marginTop: 12 },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 40,
    right: 40,
    fontSize: 9,
    color: '#8891a0',
    borderTop: 1,
    borderColor: '#d1d5db',
    paddingTop: 6,
  },
})

export const InvoiceTemplate: React.FC<{ data: InvoiceData }> = ({ data }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.header}>KerjaCUS! Invoice</Text>

      <View style={styles.section}>
        <View style={styles.row}>
          <Text style={styles.label}>Invoice #</Text>
          <Text style={styles.value}>{data.invoiceNumber}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Issued</Text>
          <Text style={styles.value}>{new Date(data.issuedAt).toLocaleDateString('id-ID')}</Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={[styles.label, { marginBottom: 4 }]}>Project Owner</Text>
        <Text style={styles.value}>{data.owner.name}</Text>
        <Text style={[styles.value, { fontSize: 10 }]}>{data.owner.email}</Text>
      </View>

      <View style={styles.section}>
        <Text style={[styles.label, { marginBottom: 4 }]}>Talent</Text>
        <Text style={styles.value}>{data.talent.name}</Text>
        {!data.isAdminCopy && (
          <Text style={[styles.value, { fontSize: 10 }]}>{data.talent.email}</Text>
        )}
      </View>

      <View style={styles.table}>
        <View style={styles.row}>
          <Text style={styles.label}>Project</Text>
          <Text style={styles.value}>{data.projectTitle}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Milestone</Text>
          <Text style={styles.value}>{data.milestoneTitle}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Description</Text>
          <Text style={styles.value}>{data.milestoneDescription}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Payment method</Text>
          <Text style={styles.value}>{data.paymentMethod}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Payment ref</Text>
          <Text style={styles.value}>{data.paymentRef}</Text>
        </View>
      </View>

      <View style={[styles.row, { marginTop: 20 }]}>
        <Text style={styles.label}>Total Amount</Text>
        <Text style={styles.total}>Rp {data.amount.toLocaleString('id-ID')}</Text>
      </View>

      {data.isAdminCopy && data.platformFee !== undefined && (
        <View style={[styles.row, { marginTop: 8 }]}>
          <Text style={styles.label}>Platform fee (admin copy)</Text>
          <Text style={styles.value}>Rp {data.platformFee.toLocaleString('id-ID')}</Text>
        </View>
      )}

      <Text style={styles.footer}>
        Generated by KerjaCUS! — managed marketplace for digital projects in Indonesia.
      </Text>
    </Page>
  </Document>
)
