// Code generated by apps/notification-service/scripts/generate-notification-templates.ts. DO NOT EDIT.
// Source of truth: packages/shared/src/notification-templates.ts

package notify

// Template is one notification's wording in one language.
type Template struct {
	Title   string
	Message string
}

// Entry holds every language a template ships in, keyed by the value stored in
// user.locale.
type Entry struct {
	ByLocale map[string]Template
}

// Templates is the catalog. Keys are the values written to
// notifications.template_key and read back by the frontend.
var Templates = map[string]Entry{
	"notification.admin_ai_degraded": {
		ByLocale: map[string]Template{
			"id": {Title: "Layanan AI bermasalah", Message: "{{errors}} dari {{total}} panggilan AI gagal dalam satu jam terakhir. Scoping, pembuatan dokumen, parsing CV, dan embedding semuanya bergantung padanya. Periksa key provider dan log ai-service."},
			"en": {Title: "AI service is failing", Message: "{{errors}} of {{total}} AI calls failed in the last hour. Scoping, document generation, CV parsing and embeddings all depend on it. Check the provider key and the ai-service logs."},
		},
	},
	"notification.admin_milestone_rejected": {
		ByLocale: map[string]Template{
			"id": {Title: "Milestone ditolak", Message: "Milestone {{milestoneId}} di proyek {{projectId}} ditolak. Cocokkan dengan scope yang disepakati."},
			"en": {Title: "Milestone rejected", Message: "Milestone {{milestoneId}} on project {{projectId}} was rejected. Check it against the agreed scope."},
		},
	},
	"notification.admin_new_dispute": {
		ByLocale: map[string]Template{
			"id": {Title: "Sengketa baru dibuka", Message: "Ada sengketa baru yang perlu dimediasi. Escrow proyeknya dibekukan."},
			"en": {Title: "New dispute opened", Message: "A dispute was opened and needs mediation. Escrow on the project is frozen."},
		},
	},
	"notification.admin_project_start_overdue": {
		ByLocale: map[string]Template{
			"id": {Title: "Proyek belum dimulai", Message: "Proyek {{projectId}} melewati tenggat mulai dan escrow-nya sudah terisi."},
			"en": {Title: "Project has not started", Message: "Project {{projectId}} has held matched past the start deadline with escrow funded."},
		},
	},
	"notification.admin_revision_exhausted": {
		ByLocale: map[string]Template{
			"id": {Title: "Jatah revisi habis", Message: "Milestone {{milestoneId}} di proyek {{projectId}} sudah memakai seluruh revisi gratisnya. Cocokkan dengan scope yang disepakati."},
			"en": {Title: "Revision rounds exhausted", Message: "Milestone {{milestoneId}} on project {{projectId}} has used every free revision. Check it against the agreed scope."},
		},
	},
	"notification.admin_team_escalated": {
		ByLocale: map[string]Template{
			"id": {Title: "Pembentukan tim perlu perhatian", Message: "Proyek {{projectId}} melewati tenggat pembentukan tim ({{reason}})."},
			"en": {Title: "Team formation needs attention", Message: "Project {{projectId}} passed the team formation deadline ({{reason}})."},
		},
	},
	"notification.application_accepted": {
		ByLocale: map[string]Template{
			"id": {Title: "Lamaran Anda diterima", Message: "Pemilik proyek menerima lamaran Anda. Buka proyeknya untuk melihat pekerjaannya."},
			"en": {Title: "Your application was accepted", Message: "The owner accepted your application. Open the project to see the work."},
		},
	},
	"notification.application_created": {
		ByLocale: map[string]Template{
			"id": {Title: "Ada talenta melamar proyek Anda", Message: "Seseorang melamar proyek Anda. Tinjau profil anonimnya dan tentukan siapa yang bergabung."},
			"en": {Title: "A talent applied to your project", Message: "Someone applied to your project. Review the anonymous profile and decide who joins."},
		},
	},
	"notification.application_rejected": {
		ByLocale: map[string]Template{
			"id": {Title: "Lamaran Anda belum dipilih", Message: "Pemilik proyek memilih talenta lain untuk proyek ini. Lamaran Anda yang lain tidak terpengaruh."},
			"en": {Title: "Your application was not selected", Message: "The owner has chosen another talent for this project. Your other applications are unaffected."},
		},
	},
	"notification.assignment_declined": {
		ByLocale: map[string]Template{
			"id": {Title: "Seorang talenta menolak tawaran", Message: "Satu posisi di proyek Anda terbuka lagi. Pilih penggantinya dari halaman pencocokan."},
			"en": {Title: "A talent declined their offer", Message: "A position on your project reopened. Pick a replacement from the matching page."},
		},
	},
	"notification.assignment_offer": {
		ByLocale: map[string]Template{
			"id": {Title: "Ada tawaran pekerjaan baru", Message: "Ada tawaran work package yang menunggu Anda. Terima atau tolak dari dashboard Anda."},
			"en": {Title: "New assignment offer", Message: "You have a work package offer waiting. Accept or decline it from your dashboard."},
		},
	},
	"notification.contract_executed": {
		ByLocale: map[string]Template{
			"id": {Title: "Semua perjanjian sudah ditandatangani", Message: "Seluruh NDA dan perjanjian pengalihan HKI di proyek ini sudah ditandatangani. Pengerjaan bisa dimulai."},
			"en": {Title: "Every agreement is signed", Message: "All NDAs and IP transfer agreements on this project are signed. Work can start."},
		},
	},
	"notification.contract_ready": {
		ByLocale: map[string]Template{
			"id": {Title: "Perjanjian siap ditandatangani", Message: "NDA dan perjanjian pengalihan HKI untuk {{roleLabel}} sudah siap. Pengerjaan belum bisa dimulai sebelum Anda dan talenta sama-sama menandatanganinya."},
			"en": {Title: "Agreements are ready to sign", Message: "The NDA and IP transfer agreement for {{roleLabel}} are ready. Work cannot start until both you and the talent have signed."},
		},
	},
	"notification.contract_ready_talent": {
		ByLocale: map[string]Template{
			"id": {Title: "Perjanjian siap ditandatangani", Message: "NDA dan perjanjian pengalihan HKI untuk posisi Anda sudah siap. Pengerjaan belum bisa dimulai sebelum Anda dan pemilik proyek sama-sama menandatanganinya."},
			"en": {Title: "Agreements are ready to sign", Message: "The NDA and IP transfer agreement for your position are ready. Work cannot start until both you and the owner have signed."},
		},
	},
	"notification.dispute_created": {
		ByLocale: map[string]Template{
			"id": {Title: "Ada sengketa di proyek Anda", Message: "Pihak lain membuka sengketa. Dana escrow dibekukan selama sengketa berjalan. Anda punya tiga hari kerja untuk menyelesaikannya langsung sebelum admin turun tangan."},
			"en": {Title: "A dispute was opened on your project", Message: "The other party opened a dispute. Escrow is frozen while it is open. You have three working days to settle it directly before an admin mediates."},
		},
	},
	"notification.dispute_resolved": {
		ByLocale: map[string]Template{
			"id": {Title: "Sengketa Anda sudah diputuskan", Message: "Sengketa di proyek Anda sudah selesai dan dana escrow dilepas sesuai keputusan."},
			"en": {Title: "Your dispute was resolved", Message: "The dispute on your project was resolved and the escrow was released accordingly."},
		},
	},
	"notification.dispute_resolved_funds_to_owner": {
		ByLocale: map[string]Template{
			"id": {Title: "Sengketa Anda sudah diputuskan", Message: "Sengketa diputuskan memenangkan pemilik proyek dan dana yang ditahan dikembalikan."},
			"en": {Title: "Your dispute was resolved", Message: "The dispute was resolved in the owner's favour and the held funds were refunded."},
		},
	},
	"notification.dispute_resolved_funds_to_talent": {
		ByLocale: map[string]Template{
			"id": {Title: "Sengketa Anda sudah diputuskan", Message: "Sengketa diputuskan memenangkan talenta dan dana yang ditahan dicairkan."},
			"en": {Title: "Your dispute was resolved", Message: "The dispute was resolved in the talent's favour and the held funds were released."},
		},
	},
	"notification.dispute_resolved_split": {
		ByLocale: map[string]Template{
			"id": {Title: "Sengketa Anda sudah diputuskan", Message: "Sengketa diputuskan dengan membagi dana yang ditahan ke kedua pihak."},
			"en": {Title: "Your dispute was resolved", Message: "The dispute was resolved with the held funds split between both sides."},
		},
	},
	"notification.milestone_approved": {
		ByLocale: map[string]Template{
			"id": {Title: "Milestone disetujui", Message: "Milestone Anda disetujui. Pembayaran {{amount, currency}} akan dicairkan."},
			"en": {Title: "Milestone approved", Message: "Your milestone has been approved. Payment of {{amount, currency}} will be released."},
		},
	},
	"notification.milestone_auto_released": {
		ByLocale: map[string]Template{
			"id": {Title: "Milestone disetujui otomatis", Message: "Jendela tinjauan 14 hari sudah lewat, jadi milestone ini disetujui otomatis dan {{amount, currency}} dicairkan."},
			"en": {Title: "Milestone auto-approved", Message: "The 14-day review window closed, so this milestone was approved automatically and {{amount, currency}} released."},
		},
	},
	"notification.milestone_due_soon": {
		ByLocale: map[string]Template{
			"id": {Title: "Milestone segera jatuh tempo", Message: "Milestone Anda jatuh tempo dalam {{days}} hari ke depan."},
			"en": {Title: "Milestone due soon", Message: "Your milestone is due within the next {{days}} days."},
		},
	},
	"notification.milestone_overdue": {
		ByLocale: map[string]Template{
			"id": {Title: "Milestone lewat tenggat", Message: "Milestone Anda sudah lewat tenggat. Segera kirimkan hasilnya."},
			"en": {Title: "Milestone overdue", Message: "Your milestone is past due. Please submit as soon as possible."},
		},
	},
	"notification.milestone_rejected": {
		ByLocale: map[string]Template{
			"id": {Title: "Milestone ditolak", Message: "Kiriman milestone Anda ditolak. Silakan baca catatan dari pemilik proyek."},
			"en": {Title: "Milestone rejected", Message: "Your milestone submission has been rejected. Please review the feedback."},
		},
	},
	"notification.milestone_submitted": {
		ByLocale: map[string]Template{
			"id": {Title: "Milestone dikirim", Message: "Ada milestone yang dikirim dan menunggu tinjauan Anda."},
			"en": {Title: "Milestone submitted", Message: "A milestone has been submitted for your review."},
		},
	},
	"notification.payment_released": {
		ByLocale: map[string]Template{
			"id": {Title: "Pembayaran dicairkan", Message: "Pembayaran {{amount, currency}} sudah dicairkan untuk milestone Anda."},
			"en": {Title: "Payment released", Message: "Payment of {{amount, currency}} has been released for your milestone."},
		},
	},
	"notification.project_completed": {
		ByLocale: map[string]Template{
			"id": {Title: "Proyek selesai", Message: "Proyek Anda sudah ditandai selesai."},
			"en": {Title: "Project completed", Message: "Your project has been marked as completed."},
		},
	},
	"notification.project_decision_overdue": {
		ByLocale: map[string]Template{
			"id": {Title: "PRD Anda menunggu keputusan", Message: "PRD Anda sudah disetujui dan proyeknya belum bergerak. Danai proyeknya untuk mulai mencari talenta, atau ambil PRD-nya dan tutup proyek ini."},
			"en": {Title: "Your PRD is waiting on a decision", Message: "Your PRD is approved and the project has not moved since. Fund the project to start matching, or take the PRD and close it out."},
		},
	},
	"notification.project_start_overdue": {
		ByLocale: map[string]Template{
			"id": {Title: "Proyek belum dimulai", Message: "Pengerjaan proyek Anda belum dimulai sejak tim terbentuk. Hubungi tim atau minta bantuan admin untuk melepas dana escrow Anda."},
			"en": {Title: "Project has not started", Message: "Work on your project has not started since it was matched. Contact the team or ask support to release your escrow."},
		},
	},
	"notification.project_status_changed": {
		ByLocale: map[string]Template{
			"id": {Title: "Status proyek berubah", Message: "Status proyek Anda sekarang {{status}}."},
			"en": {Title: "Project status updated", Message: "Your project status is now {{status}}."},
		},
	},
	"notification.revision_requested": {
		ByLocale: map[string]Template{
			"id": {Title: "Permintaan revisi", Message: "Ada permintaan revisi untuk milestone Anda."},
			"en": {Title: "Revision requested", Message: "A revision has been requested for your milestone."},
		},
	},
	"notification.team_complete": {
		ByLocale: map[string]Template{
			"id": {Title: "Tim sudah lengkap", Message: "Semua posisi di proyek Anda sudah terisi."},
			"en": {Title: "Team formation complete", Message: "All team positions have been filled for your project."},
		},
	},
	"notification.team_escalated": {
		ByLocale: map[string]Template{
			"id": {Title: "Pembentukan tim perlu perhatian", Message: "Proyek ini belum mengisi semua posisi dalam batas 14 hari. Sesuaikan timeline atau scope-nya, atau terima tim yang sudah terkumpul."},
			"en": {Title: "Team formation needs attention", Message: "This project has not filled every position within the 14-day window. Adjust the timeline or scope, or accept the team assembled so far."},
		},
	},
	"notification.worker_overdue": {
		ByLocale: map[string]Template{
			"id": {Title: "Milestone lewat tenggat", Message: "Ada milestone di proyek Anda yang sudah lewat tanggal jatuh temponya."},
			"en": {Title: "Milestone overdue", Message: "A milestone on your project is past its due date."},
		},
	},
}
