/**
 * Emits the Go mirror of the platform fee table.
 *
 * packages/shared/src/pricing.ts is the single source of truth for the split
 * between the talent and the platform, but payment-service is Go and cannot
 * import it. Rather than hand-copy the table - where a silent divergence would
 * mean the service validating releases against a rate the platform no longer
 * charges - it is generated here and CI fails if the checked-in output drifts.
 *
 * Both vector sets are produced by running the TypeScript itself - project
 * vectors through computeProjectPricing, milestone vectors through
 * milestoneFeeFromTotals - so the Go rounding is asserted against the real
 * implementation rather than a second reading of the spec.
 *
 * The milestone arithmetic used to be restated here by hand, because
 * computeMilestoneFee calls getDb() and could not be imported without a
 * database. That was the check's one blind spot: changing its rounding order
 * left pricing.ts untouched, so CI stayed green while payment-service would
 * refuse every settlement. The pure arithmetic now lives in pricing.ts and
 * computeMilestoneFee only does the lookups that feed it.
 *
 * Usage: bun run apps/payment-service/scripts/generate-pricing.ts
 *        bun run apps/payment-service/scripts/generate-pricing.ts --check
 */
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  computeProjectPricing,
  milestoneFeeFromTotals,
  PLATFORM_FEE_BRACKETS,
  PLATFORM_FEE_TOP_BRACKET,
  talentShareRate,
} from '../../../packages/shared/src/pricing'

const GENERATOR = 'apps/payment-service/scripts/generate-pricing.ts'
const SOURCE = 'packages/shared/src/pricing.ts'
const outDir = join(dirname(fileURLToPath(import.meta.url)), '..', 'internal', 'pricing')

function header(): string {
  return [
    `// Code generated by ${GENERATOR}. DO NOT EDIT.`,
    `// Source of truth: ${SOURCE}`,
    '',
    'package pricing',
    '',
  ].join('\n')
}

function bracketsFile(): string {
  const rows = PLATFORM_FEE_BRACKETS.map(
    (b) => `\t{MaxFee: ${b.maxFee}, TalentShare: ${b.talentShare}, FeeRate: ${b.feeRate}},`,
  ).join('\n')

  return `${header()}
// Bracket is one row of the platform fee table. A project fee at or below
// MaxFee splits at these rates; the platform's share rises with project size.
type Bracket struct {
	MaxFee      int64
	TalentShare float64
	FeeRate     float64
}

// Brackets is the published table, ordered by ascending MaxFee. The comparison
// is inclusive: a fee of exactly MaxFee belongs to that bracket.
var Brackets = []Bracket{
${rows}
}

// TopShare applies above the last bracket's MaxFee.
var TopShare = struct {
	TalentShare float64
	FeeRate     float64
}{TalentShare: ${PLATFORM_FEE_TOP_BRACKET.talentShare}, FeeRate: ${PLATFORM_FEE_TOP_BRACKET.feeRate}}
`
}

/** Project fees that exercise both sides of every bracket edge, plus rounding. */
function projectFees(): number[] {
  const fees = new Set<number>([1, 999, 7_777_777, 33_333_333, 99_999_999])
  for (const b of PLATFORM_FEE_BRACKETS) {
    fees.add(b.maxFee - 1)
    fees.add(b.maxFee)
    fees.add(b.maxFee + 1)
  }
  // Odd rupiah figures: talentShare * fee lands on a .5 for several of these,
  // which is where Go's math.Round and JS Math.round could part company.
  for (const odd of [3, 5, 7, 11, 13, 101, 1_001, 2_000_001]) fees.add(odd)
  return [...fees].sort((a, b) => a - b)
}

function projectVectors(): string {
  return projectFees()
    .map((fee) => {
      const priced = computeProjectPricing([{ amount: fee }])
      return `\t{FinalPrice: ${fee}, TalentPayout: ${priced.talentPayout}, PlatformFee: ${priced.platformFee}},`
    })
    .join('\n')
}

/**
 * Milestone fees, computed by the same function computeMilestoneFee uses: the
 * ratio is the work package's talent_payout / amount, never a bracket lookup on
 * the milestone's own amount.
 */
function milestoneVectors(): string {
  const seen = new Set<string>()
  const rows: string[] = []

  for (const gross of projectFees()) {
    const payout = Math.round(gross * talentShareRate(gross))
    const amounts = [1, 3, Math.floor(gross / 3), Math.floor(gross / 2), gross - 1, gross]
    for (const amount of amounts) {
      if (amount <= 0 || amount > gross) continue
      const key = `${gross}:${amount}`
      if (seen.has(key)) continue
      seen.add(key)
      // The real implementation, imported - not a second reading of the spec.
      // null is the case computeMilestoneFee refuses to price and pays the
      // talent in full; the Go side is pinned to reject exactly those.
      const computed = milestoneFeeFromTotals(amount, payout, gross)
      const anomalous = computed === null
      const fee = computed ?? 0
      rows.push(
        `\t{Gross: ${gross}, Payout: ${payout}, Amount: ${amount}, Fee: ${fee}, Anomalous: ${anomalous}},`,
      )
    }
  }
  return rows.join('\n')
}

function goldenFile(): string {
  return `${header()}
// ProjectVector is a project priced by computeProjectPricing in ${SOURCE}.
type ProjectVector struct {
	FinalPrice   int64
	TalentPayout int64
	PlatformFee  int64
}

// MilestoneVector is a milestone fee derived from its work package ratio, the
// way computeMilestoneFee in project-service derives it. Anomalous marks the
// cases that trip the TypeScript guard, where it abandons the ratio and pays
// the talent in full; Go refuses the release there instead.
type MilestoneVector struct {
	Gross     int64
	Payout    int64
	Amount    int64
	Fee       int64
	Anomalous bool
}

var ProjectVectors = []ProjectVector{
${projectVectors()}
}

var MilestoneVectors = []MilestoneVector{
${milestoneVectors()}
}
`
}

const outputs: Record<string, string> = {
  'brackets_gen.go': bracketsFile(),
  'golden_gen_test.go': goldenFile(),
}

/*
--check re-renders in memory and byte-compares, rather than regenerating and
asking git whether anything moved. The generated files are ordinary tracked
sources on some branches and untracked on others, and `git diff --exit-code`
never sees the untracked case - a drift check built on it would report success
whatever the generator emitted.
*/
if (process.argv.includes('--check')) {
  const stale: string[] = []
  for (const [name, want] of Object.entries(outputs)) {
    // Missing counts as stale: a deleted generated file must fail the check,
    // not read as "nothing to compare".
    const got = await readFile(join(outDir, name), 'utf8').catch(() => '')
    if (got !== want) stale.push(name)
  }

  if (stale.length > 0) {
    console.error(`${SOURCE} has changed but ${stale.join(', ')} was not regenerated.`)
    console.error(`Run: bun run ${GENERATOR}`)
    process.exit(1)
  }
  console.log(`${Object.keys(outputs).length} generated files match ${SOURCE}`)
} else {
  for (const [name, contents] of Object.entries(outputs)) {
    await writeFile(join(outDir, name), contents, 'utf8')
  }
  console.log(`wrote ${Object.keys(outputs).join(', ')} to ${outDir}`)
}
