#!/usr/bin/env bash
# DO NOT EDIT. Generated by scripts/generate-cloudflare-ips.ts
#
# Allow 80/443 at the origin only from Cloudflare.
#
# Run this only after api.kerjacus.id and every other public hostname is
# proxied through Cloudflare. While a hostname is DNS-only its visitors reach
# the origin directly, and this script is precisely what stops that.
#
#   sudo bash infra/cloudflare-origin-firewall.sh apply
#   sudo bash infra/cloudflare-origin-firewall.sh revert
#
# Rules live in memory. Persist with netfilter-persistent once the site is
# confirmed healthy, never before - a reboot is the fastest way back.
set -euo pipefail

IFACE="${KC_PUBLIC_IFACE:-eth0}"
PORTS="80,443"

apply() {
  for cmd in iptables ip6tables; do
    $cmd -N KC-CF-ONLY 2>/dev/null || $cmd -F KC-CF-ONLY
    # Replies to connections the origin itself opened.
    $cmd -A KC-CF-ONLY -m conntrack --ctstate RELATED,ESTABLISHED -j RETURN
  done

  iptables -A KC-CF-ONLY -s 173.245.48.0/20 -j RETURN
  iptables -A KC-CF-ONLY -s 103.21.244.0/22 -j RETURN
  iptables -A KC-CF-ONLY -s 103.22.200.0/22 -j RETURN
  iptables -A KC-CF-ONLY -s 103.31.4.0/22 -j RETURN
  iptables -A KC-CF-ONLY -s 141.101.64.0/18 -j RETURN
  iptables -A KC-CF-ONLY -s 108.162.192.0/18 -j RETURN
  iptables -A KC-CF-ONLY -s 190.93.240.0/20 -j RETURN
  iptables -A KC-CF-ONLY -s 188.114.96.0/20 -j RETURN
  iptables -A KC-CF-ONLY -s 197.234.240.0/22 -j RETURN
  iptables -A KC-CF-ONLY -s 198.41.128.0/17 -j RETURN
  iptables -A KC-CF-ONLY -s 162.158.0.0/15 -j RETURN
  iptables -A KC-CF-ONLY -s 104.16.0.0/13 -j RETURN
  iptables -A KC-CF-ONLY -s 104.24.0.0/14 -j RETURN
  iptables -A KC-CF-ONLY -s 172.64.0.0/13 -j RETURN
  iptables -A KC-CF-ONLY -s 131.0.72.0/22 -j RETURN

  ip6tables -A KC-CF-ONLY -s 2400:cb00::/32 -j RETURN
  ip6tables -A KC-CF-ONLY -s 2606:4700::/32 -j RETURN
  ip6tables -A KC-CF-ONLY -s 2803:f800::/32 -j RETURN
  ip6tables -A KC-CF-ONLY -s 2405:b500::/32 -j RETURN
  ip6tables -A KC-CF-ONLY -s 2405:8100::/32 -j RETURN
  ip6tables -A KC-CF-ONLY -s 2a06:98c0::/29 -j RETURN
  ip6tables -A KC-CF-ONLY -s 2c0f:f248::/32 -j RETURN

  for cmd in iptables ip6tables; do
    $cmd -A KC-CF-ONLY -j DROP
    # Idempotent: drop any previous hook before adding this one.
    while $cmd -D DOCKER-USER -i "$IFACE" -p tcp -m multiport --dports "$PORTS" -j KC-CF-ONLY 2>/dev/null; do :; done
    $cmd -I DOCKER-USER -i "$IFACE" -p tcp -m multiport --dports "$PORTS" -j KC-CF-ONLY
  done

  echo "Applied. Confirm the site is up, then persist with:"
  echo "  sudo netfilter-persistent save"
}

revert() {
  for cmd in iptables ip6tables; do
    while $cmd -D DOCKER-USER -i "$IFACE" -p tcp -m multiport --dports "$PORTS" -j KC-CF-ONLY 2>/dev/null; do :; done
    $cmd -F KC-CF-ONLY 2>/dev/null || true
    $cmd -X KC-CF-ONLY 2>/dev/null || true
  done
  echo "Reverted."
}

case "${1:-}" in
  apply) apply ;;
  revert) revert ;;
  *) echo "usage: $0 apply|revert" >&2; exit 2 ;;
esac
