/**
 * Emits the Python mirror of the scoping completeness table.
 *
 * packages/shared/src/scoping-completeness.ts is the single source of truth for
 * which eleven things a scoping conversation has to cover and which words count
 * as covering them. ai-service scores the chat transcript against that table and
 * project-service scores the intake form against it, but ai-service is Python
 * and cannot import the TypeScript.
 *
 * The two tables were maintained separately and happened to still agree. The
 * fee table and the OTLP helpers are both recorded in CLAUDE.md as the same
 * arrangement after it stopped agreeing, so this generates the copy instead and
 * CI fails when the checked-in output drifts.
 *
 * Usage: bun run apps/ai-service/scripts/generate-completeness.ts
 *        bun run apps/ai-service/scripts/generate-completeness.ts --check
 */
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  COMPLETENESS_KEYS,
  COMPLETENESS_KEYWORDS,
  DESCRIPTION_MIN_CHARS,
  REQUIREMENTS_MIN_CHARS,
} from '../../../packages/shared/src/scoping-completeness'

const GENERATOR = 'apps/ai-service/scripts/generate-completeness.ts'
const SOURCE = 'packages/shared/src/scoping-completeness.ts'
const outFile = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'app',
  'services',
  'completeness_keywords.py',
)

function quote(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}

function render(): string {
  const keys = COMPLETENESS_KEYS.map((key) => `    ${quote(key)},`).join('\n')
  const table = Object.entries(COMPLETENESS_KEYWORDS)
    .map(([key, words]) => {
      const items = (words as readonly string[]).map((w) => `        ${quote(w)},`).join('\n')
      return `    ${quote(key)}: (\n${items}\n    ),`
    })
    .join('\n')

  return `# Code generated by ${GENERATOR}. DO NOT EDIT.
# Source of truth: ${SOURCE}

# Scoring order, which is the order identify_missing returns and the order the
# scoping page renders the "still needed" chips in.
COMPLETENESS_KEYS: tuple[str, ...] = (
${keys}
)

# A section counts as covered when the lowercased text names any of its words.
# "description" is absent on purpose: it is measured by length alone.
COMPLETENESS_KEYWORDS: dict[str, tuple[str, ...]] = {
${table}
}

# Length floors over the joined user text, not over one section.
DESCRIPTION_MIN_CHARS = ${DESCRIPTION_MIN_CHARS}
REQUIREMENTS_MIN_CHARS = ${REQUIREMENTS_MIN_CHARS}
`
}

const wanted = render()

if (process.argv.includes('--check')) {
  const current = await readFile(outFile, 'utf8').catch(() => '')
  if (current !== wanted) {
    console.error(`${outFile} is out of date. Run: bun run ${GENERATOR}`)
    process.exit(1)
  }
  console.log('completeness table is in sync')
} else {
  await writeFile(outFile, wanted)
  console.log(`wrote ${outFile}`)
}
