/**
 * Emits the per-service copies of the shared Go observability plumbing.
 *
 * payment-service, notification-service and admin-service each carry their own
 * internal/observability package. The files are infrastructure - OTLP wiring
 * and trace-context propagation - and were maintained as three hand-copies.
 * otel.go stayed byte-identical, but nats.go had already drifted in
 * admin-service, which is what happens to copies nobody diffs.
 *
 * A shared Go module was evaluated and rejected: all three Dockerfiles do
 * `COPY go.mod go.sum` with `context: ./apps/<svc>`, so a `replace` target
 * outside the build context breaks the image build, and a go.work file never
 * gets copied in. Fixing that costs three Dockerfile rewrites, three compose
 * context moves and a .dockerignore. Generation costs this file and one CI
 * step, and buys the same guarantee: a change to the canonical copy cannot
 * land in one service and miss the other two.
 *
 * The canonical sources are ordinary .go files rather than templates, so the
 * bytes here are the bytes that ship and gofmt reads them as Go. They sit
 * outside every go.mod, so an editor will report their imports as
 * unresolvable; that is the accepted cost of not owning them from inside one
 * of the three services. Type errors still surface, on the generated copies,
 * in the test-go and build-go jobs.
 *
 * Usage: bun run packages/go-observability/generate.ts
 *        bun run packages/go-observability/generate.ts --check
 */
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const GENERATOR = 'packages/go-observability/generate.ts'
const SOURCE_DIR = 'packages/go-observability'

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(here, '..', '..')

/*
Listed rather than globbed. Adding a file to the shared set means adding it to
every service, which should be a deliberate edit here and not a side effect of
dropping a file into the directory.
*/
const FILES = ['otel.go', 'nats.go', 'trace_context.go']
const SERVICES = ['payment-service', 'notification-service', 'admin-service']

/*
Two lines then a blank one: the marker has to precede the package clause for Go
to recognise the file as generated, and the blank line stops it being read as
the package doc comment.
*/
function header(name: string): string {
  return [
    `// Code generated by ${GENERATOR}. DO NOT EDIT.`,
    `// Source of truth: ${SOURCE_DIR}/${name}`,
    '',
    '',
  ].join('\n')
}

const outputs = new Map<string, string>()
for (const name of FILES) {
  const contents = header(name) + (await readFile(join(here, name), 'utf8'))
  for (const service of SERVICES) {
    outputs.set(join(repoRoot, 'apps', service, 'internal', 'observability', name), contents)
  }
}

/*
--check re-renders in memory and byte-compares rather than regenerating and
asking git what moved, matching apps/payment-service/scripts/generate-pricing.ts.
A missing file counts as stale: deleting a generated copy has to fail the check,
not read as "nothing to compare".
*/
if (process.argv.includes('--check')) {
  const stale: string[] = []
  for (const [path, want] of outputs) {
    const got = await readFile(path, 'utf8').catch(() => '')
    if (got !== want) stale.push(relative(repoRoot, path))
  }

  if (stale.length > 0) {
    console.error(`${SOURCE_DIR} has changed but these copies were not regenerated:`)
    for (const path of stale) console.error(`  ${path}`)
    console.error(`Run: bun run ${GENERATOR}`)
    process.exit(1)
  }
  console.log(`${outputs.size} generated files match ${SOURCE_DIR}`)
} else {
  for (const [path, contents] of outputs) {
    await writeFile(path, contents, 'utf8')
  }
  console.log(`wrote ${FILES.length} files into ${SERVICES.length} services`)
}
