// Code generated by packages/go-observability/generate.ts. DO NOT EDIT.
// Source of truth: packages/go-observability/trace_context.go

package observability

import (
	"context"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/propagation"
)

// CaptureTraceContext serializes the active trace context for JSONB persistence.
func CaptureTraceContext(ctx context.Context) map[string]string {
	carrier := propagation.MapCarrier{}
	otel.GetTextMapPropagator().Inject(ctx, carrier)
	if len(carrier) == 0 {
		return nil
	}
	return carrier
}

// RestoreTraceContext rehydrates a persisted carrier into ctx.
func RestoreTraceContext(ctx context.Context, m map[string]string) context.Context {
	if len(m) == 0 {
		return ctx
	}
	return otel.GetTextMapPropagator().Extract(ctx, propagation.MapCarrier(m))
}
