/**
 * What a scoping conversation has to cover before a BRD can be generated.
 *
 * The same eleven checks are scored in two places: the AI service scores the
 * chat transcript, and project-service scores the intake form to give the chat
 * a floor. Both tables were written out by hand in their own language, which is
 * the arrangement CLAUDE.md already records going wrong for the fee table and
 * the OTLP wiring. They had not drifted yet; this is what stops the first edit
 * that would.
 *
 * The Python copy is generated by apps/ai-service/scripts/generate-completeness.ts
 * and CI fails when the checked-in output no longer matches this file.
 *
 * Keys are also the i18n suffixes behind the "still needed" chips
 * (missing_problem, missing_budget and so on), so renaming one is a UI change.
 */

/** Scoring order, which is the order the chips are rendered in. */
export const COMPLETENESS_KEYS = [
  'description',
  'problem',
  'objectives',
  'features',
  'users',
  'requirements',
  'risks',
  'metrics',
  'budget',
  'timeline',
  'integrations',
] as const

export type CompletenessKey = (typeof COMPLETENESS_KEYS)[number]

/**
 * A section counts as covered when the text names any of its words.
 *
 * Indonesian and English sit in one list because owners mix them freely inside
 * a single sentence, and the check runs over lowercased text.
 *
 * `description` is absent on purpose: it is measured by length alone, which is
 * the weakest check here and the reason the bar can move without the owner
 * having answered anything.
 */
export const COMPLETENESS_KEYWORDS: Record<
  Exclude<CompletenessKey, 'description'>,
  readonly string[]
> = {
  problem: [
    'masalah',
    'problem',
    'kendala',
    'pain',
    'isu',
    'issue',
    'saat ini',
    'currently',
    'manual',
    'tidak bisa',
    'belum ada',
  ],
  objectives: [
    'tujuan',
    'goal',
    'objective',
    'target',
    'ingin',
    'mau',
    'want',
    'meningkatkan',
    'increase',
    'menurunkan',
    'reduce',
  ],
  features: [
    'fitur',
    'feature',
    'fungsi',
    'function',
    'modul',
    'module',
    'halaman',
    'page',
    'dashboard',
    'login',
    'register',
  ],
  users: [
    'user',
    'pengguna',
    'pelanggan',
    'customer',
    'target',
    'audience',
    'admin',
    'konsumen',
    'pembeli',
    'buyer',
  ],
  requirements: [
    'harus',
    'must',
    'perlu',
    'need',
    'require',
    'wajib',
    'sistem',
    'system',
    'data',
    'laporan',
    'report',
  ],
  risks: [
    'risiko',
    'risk',
    'asumsi',
    'assumption',
    'keterbatasan',
    'constraint',
    'tantangan',
    'challenge',
    'hambatan',
  ],
  metrics: [
    'metrik',
    'metric',
    'kpi',
    'ukur',
    'measure',
    'sukses',
    'success',
    'persentase',
    'percent',
    'angka',
    'number',
    'target',
  ],
  budget: ['budget', 'biaya', 'harga', 'anggaran', 'rp', 'juta', 'ribu', 'million', 'cost', 'dana'],
  timeline: [
    'deadline',
    'waktu',
    'timeline',
    'kapan',
    'bulan',
    'minggu',
    'hari',
    'day',
    'week',
    'month',
    'selesai',
    'launch',
  ],
  integrations: [
    'integrasi',
    'integration',
    'api',
    'payment',
    'pembayaran',
    'whatsapp',
    'google',
    'midtrans',
    'xendit',
    'notifikasi',
  ],
}

/**
 * Length floors, measured over the joined text rather than one section.
 *
 * They are proxies for substance and weak ones: `description` is satisfied by
 * any 80 characters at all, and `requirements` measures the whole
 * conversation. Left as they are because moving them moves the number the
 * Generate BRD control is gated on, which is a product decision.
 */
export const DESCRIPTION_MIN_CHARS = 80
export const REQUIREMENTS_MIN_CHARS = 300
