/**
 * Which facts a scoping conversation has to establish before a BRD is worth
 * generating, who supplies each one, and what to ask when it is absent.
 *
 * This file is the denominator of the completeness percentage, the list the
 * chatbot asks from, and the boundary between what the owner is asked for and
 * what the platform derives. All three read the same table so they cannot
 * describe different gaps.
 *
 * The governing assumption: a project owner is a business stakeholder, not a
 * technologist. Every scored field must be answerable by someone who has never
 * chosen a framework. Anything technical is derived at PRD time and never
 * scored, so a fully cooperative owner reaches 100 without naming a single
 * piece of technology. `owner_answerable.test.ts` asserts that property.
 *
 * Keys are i18n suffixes behind the "still needed" chips (missing_problem,
 * missing_budget) and the question prompts, so renaming one is a UI change.
 *
 * The Python copy is generated by apps/ai-service/scripts/generate-completeness.ts
 * and CI fails when the checked-in output no longer matches this file.
 */

/** Where a field's answer comes from. */
export type ScopingFieldSource = 'form' | 'chat'

/** Which document the field is a prerequisite for. */
export type ScopingFieldStage = 'brd' | 'prd'

export type ScopingField = {
  readonly key: string
  readonly source: ScopingFieldSource
  readonly stage: ScopingFieldStage
  /**
   * Degrade path only. Extraction over the transcript decides coverage; these
   * words decide it when extraction is unavailable. A form field has none
   * because reading the column cannot fail in a way words would rescue.
   */
  readonly fallbackKeywords: readonly string[]
}

/**
 * Scoring order, which is the order the chips render in.
 *
 * Six form fields, five chat fields for the BRD, three chat fields the PRD
 * needs. The form already makes problem, targetUsers and mainFeatures
 * mandatory, so a project that exists at all starts with six covered. That is
 * the floor, and the five BRD chat fields are what the floor is not allowed to
 * reach on its own.
 */
export const SCOPING_FIELDS = [
  { key: 'description', source: 'form', stage: 'brd', fallbackKeywords: [] },
  { key: 'problem', source: 'form', stage: 'brd', fallbackKeywords: [] },
  { key: 'users', source: 'form', stage: 'brd', fallbackKeywords: [] },
  { key: 'features', source: 'form', stage: 'brd', fallbackKeywords: [] },
  { key: 'budget', source: 'form', stage: 'brd', fallbackKeywords: [] },
  { key: 'timeline', source: 'form', stage: 'brd', fallbackKeywords: [] },
  {
    key: 'objectives',
    source: 'chat',
    stage: 'brd',
    fallbackKeywords: [
      'tujuan',
      'goal',
      'objective',
      'meningkatkan',
      'increase',
      'menurunkan',
      'reduce',
      'menghemat',
      'mempercepat',
    ],
  },
  {
    key: 'metrics',
    source: 'chat',
    stage: 'brd',
    fallbackKeywords: [
      'metrik',
      'metric',
      'kpi',
      'ukur',
      'measure',
      'persen',
      'percent',
      'per bulan',
      'per hari',
      'per month',
    ],
  },
  {
    key: 'scope_boundary',
    source: 'chat',
    stage: 'brd',
    fallbackKeywords: [
      'tidak termasuk',
      'di luar',
      'out of scope',
      'exclude',
      'belum perlu',
      'nanti saja',
      'fase berikutnya',
      'later phase',
    ],
  },
  {
    key: 'stakeholders',
    source: 'chat',
    stage: 'brd',
    fallbackKeywords: [
      'stakeholder',
      'pemangku',
      'yang memutuskan',
      'approval',
      'menyetujui',
      'tim saya',
      'divisi',
      'atasan',
      'owner',
      'manajer',
    ],
  },
  {
    key: 'constraints',
    source: 'chat',
    stage: 'brd',
    fallbackKeywords: [
      'risiko',
      'risk',
      'asumsi',
      'assumption',
      'keterbatasan',
      'constraint',
      'kendala',
      'hambatan',
      'bergantung',
      'depends',
    ],
  },
  {
    key: 'integrations',
    source: 'chat',
    stage: 'prd',
    fallbackKeywords: [
      'integrasi',
      'integration',
      'whatsapp',
      'midtrans',
      'xendit',
      'tokopedia',
      'shopee',
      'accurate',
      'sistem lama',
      'existing system',
      'tidak ada integrasi',
    ],
  },
  {
    key: 'volume',
    source: 'chat',
    stage: 'prd',
    fallbackKeywords: [
      'pengguna per',
      'user per',
      'transaksi per',
      'transaction per',
      'ribu',
      'juta',
      'concurrent',
      'bersamaan',
      'traffic',
    ],
  },
  {
    key: 'business_rules',
    source: 'chat',
    stage: 'prd',
    fallbackKeywords: [
      'aturan',
      'rule',
      'kebijakan',
      'policy',
      'harus disetujui',
      'minimal',
      'maksimal',
      'kuota',
      'quota',
      'diskon',
    ],
  },
] as const satisfies readonly ScopingField[]

export type CompletenessKey = (typeof SCOPING_FIELDS)[number]['key']

/** Keys scored by the percentage that gates Generate BRD. */
export const BRD_FIELD_KEYS: readonly string[] = SCOPING_FIELDS.filter(
  (f) => f.stage === 'brd',
).map((f) => f.key)

/** Keys the PRD needs, collected after the BRD is approved. */
export const PRD_FIELD_KEYS: readonly string[] = SCOPING_FIELDS.filter(
  (f) => f.stage === 'prd',
).map((f) => f.key)

/** Keys answered by reading the project row rather than the transcript. */
export const FORM_FIELD_KEYS: readonly string[] = SCOPING_FIELDS.filter(
  (f) => f.source === 'form',
).map((f) => f.key)

/** Keys that only the transcript can answer. */
export const CHAT_FIELD_KEYS: readonly string[] = SCOPING_FIELDS.filter(
  (f) => f.source === 'chat',
).map((f) => f.key)

export const COMPLETENESS_KEYS: readonly string[] = SCOPING_FIELDS.map((f) => f.key)

/**
 * Degrade path for chat fields, keyed the same as the spec.
 *
 * Presence of a word is weak evidence and was the whole scorer until now. It
 * stays only for the case where structured extraction is unavailable, and the
 * caller records which path produced the score.
 */
export const COMPLETENESS_KEYWORDS: Record<string, readonly string[]> = Object.fromEntries(
  SCOPING_FIELDS.filter((f) => f.source === 'chat').map((f) => [f.key, f.fallbackKeywords]),
)

/**
 * Things the platform decides, so the chatbot must never ask for them.
 *
 * An owner who answers "React" is guessing, and a BRD built on that guess reads
 * as a requirement to whoever implements it. These are produced at PRD time
 * from category, scale and integrations.
 */
export const DERIVED_FIELDS: readonly string[] = [
  'tech_stack',
  'framework_versions',
  'architecture',
  'api_design',
  'database_schema',
  'hosting',
  'team_composition',
  'work_package_pricing',
  'sprint_plan',
] as const

/**
 * Minimum length of the project description before it counts as one.
 *
 * Measured over the description column alone, not the joined transcript. The
 * previous 80 was satisfied by any 80 characters anywhere in the conversation,
 * which made the check pass before the owner had described anything.
 */
export const DESCRIPTION_MIN_CHARS = 120

/**
 * Score at which the Generate BRD control is enabled.
 *
 * Eleven BRD fields, so the grain is about nine points and 82 is the first
 * value reachable with nine of eleven covered. The old 80 was a fraction of a
 * different denominator and is not carried across unchanged: it now means the
 * owner may leave at most two of the eleven unanswered, and the two it can
 * absorb are the ones a BRD survives without.
 */
export const BRD_READY_SCORE = 82
