/**
 * Cloudflare's published edge ranges, as an nginx geo block.
 *
 * The gateway decides whether to believe CF-Connecting-IP by asking whether
 * the peer that actually reached Dokploy's Traefik was Cloudflare. That
 * question needs the list, and a stale list fails in the expensive direction:
 * genuine Cloudflare traffic gets classified as direct, every visitor is keyed
 * on a handful of edge addresses, and the rate limiter locks out the platform.
 *
 * So it is generated and drift-checked rather than pasted, the same shape as
 * the fee table, the completeness keywords and the OTLP helpers. --check exits
 * non-zero when the committed file no longer matches what Cloudflare
 * publishes.
 *
 * Network failure is not drift. The check reports it and exits 0, because a CI
 * gate that goes red when a third party has a bad minute is a gate people
 * learn to rerun until it passes.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const OUTPUT = path.resolve(import.meta.dirname, '..', 'apps', 'gateway', 'cloudflare-ips.conf')
const SOURCES = ['https://www.cloudflare.com/ips-v4', 'https://www.cloudflare.com/ips-v6']

const HEADER = `# DO NOT EDIT. Generated by scripts/generate-cloudflare-ips.ts
#
# Cloudflare's edge ranges, included into a geo block that decides whether
# CF-Connecting-IP came from Cloudflare or from someone who typed it.
# Refresh with: bun run scripts/generate-cloudflare-ips.ts
`

/** CIDR, rejecting anything that is not one, since this feeds a config. */
function isCidr(line: string): boolean {
  return /^[0-9a-f.:]+\/\d{1,3}$/i.test(line)
}

async function fetchRanges(): Promise<string[]> {
  const bodies = await Promise.all(
    SOURCES.map(async (url) => {
      const res = await fetch(url, { signal: AbortSignal.timeout(15_000) })
      if (!res.ok) throw new Error(`${url} answered ${res.status}`)
      return res.text()
    }),
  )

  const ranges = bodies
    .flatMap((body) => body.split('\n'))
    .map((line) => line.trim())
    .filter(Boolean)

  const bad = ranges.filter((r) => !isCidr(r))
  if (bad.length > 0) throw new Error(`Cloudflare returned non-CIDR lines: ${bad.join(', ')}`)
  // A truncated response would silently narrow the allowlist.
  if (ranges.length < 15) throw new Error(`Only ${ranges.length} ranges returned; expected at least 15`)

  return ranges
}

function render(ranges: string[]): string {
  return `${HEADER}${ranges.map((r) => `${r} 1;`).join('\n')}\n`
}

async function main() {
  const check = process.argv.includes('--check')

  let ranges: string[]
  try {
    ranges = await fetchRanges()
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error)
    if (check) {
      console.log(`Could not reach Cloudflare (${reason}); skipping drift check.`)
      return
    }
    throw error
  }

  const next = render(ranges)

  if (check) {
    const current = readFileSync(OUTPUT, 'utf8')
    if (current === next) {
      console.log(`cloudflare-ips.conf matches Cloudflare (${ranges.length} ranges).`)
      return
    }
    console.error(
      'cloudflare-ips.conf has drifted from what Cloudflare publishes.\n' +
        'Run: bun run scripts/generate-cloudflare-ips.ts',
    )
    process.exit(1)
  }

  writeFileSync(OUTPUT, next)
  console.log(`Wrote ${ranges.length} ranges to ${path.relative(process.cwd(), OUTPUT)}`)
}

await main()
