/**
 * Cloudflare's published edge ranges, as an nginx geo block.
 *
 * The gateway decides whether to believe CF-Connecting-IP by asking whether
 * the peer that actually reached Dokploy's Traefik was Cloudflare. That
 * question needs the list, and a stale list fails in the expensive direction:
 * genuine Cloudflare traffic gets classified as direct, every visitor is keyed
 * on a handful of edge addresses, and the rate limiter locks out the platform.
 *
 * So it is generated and drift-checked rather than pasted, the same shape as
 * the fee table, the completeness keywords and the OTLP helpers. --check exits
 * non-zero when the committed file no longer matches what Cloudflare
 * publishes.
 *
 * Network failure is not drift. The check reports it and exits 0, because a CI
 * gate that goes red when a third party has a bad minute is a gate people
 * learn to rerun until it passes.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const GATEWAY = path.resolve(import.meta.dirname, '..', 'apps', 'gateway', 'cloudflare-ips.conf')
const FIREWALL = path.resolve(import.meta.dirname, '..', 'infra', 'cloudflare-origin-firewall.sh')
const SOURCES = ['https://www.cloudflare.com/ips-v4', 'https://www.cloudflare.com/ips-v6']

const HEADER = `# DO NOT EDIT. Generated by scripts/generate-cloudflare-ips.ts
#
# Cloudflare's edge ranges, included into a geo block that decides whether
# CF-Connecting-IP came from Cloudflare or from someone who typed it.
# Refresh with: bun run scripts/generate-cloudflare-ips.ts
`

/** CIDR, rejecting anything that is not one, since this feeds a config. */
function isCidr(line: string): boolean {
  return /^[0-9a-f.:]+\/\d{1,3}$/i.test(line)
}

async function fetchRanges(): Promise<string[]> {
  const bodies = await Promise.all(
    SOURCES.map(async (url) => {
      const res = await fetch(url, { signal: AbortSignal.timeout(15_000) })
      if (!res.ok) throw new Error(`${url} answered ${res.status}`)
      return res.text()
    }),
  )

  const ranges = bodies
    .flatMap((body) => body.split('\n'))
    .map((line) => line.trim())
    .filter(Boolean)

  const bad = ranges.filter((r) => !isCidr(r))
  if (bad.length > 0) throw new Error(`Cloudflare returned non-CIDR lines: ${bad.join(', ')}`)
  // A truncated response would silently narrow the allowlist.
  if (ranges.length < 15) throw new Error(`Only ${ranges.length} ranges returned; expected at least 15`)

  return ranges
}

function renderGateway(ranges: string[]): string {
  return `${HEADER}${ranges.map((r) => `${r} 1;`).join('\n')}\n`
}

/**
 * Host firewall for the origin, as a script to read before running.
 *
 * ufw is the wrong tool and reads as if it worked. Traefik publishes 80 and
 * 443 through Docker, and Docker's own rules are consulted before ufw's INPUT
 * chain, so `ufw deny 443` on a published port changes nothing while ufw
 * reports itself active. DOCKER-USER is the chain Docker evaluates first on
 * forwarded traffic and never rewrites.
 *
 * Scoped to the public interface. Without that, container-to-container traffic
 * is caught too - the web container reaches the gateway on port 80 from a
 * private address, which is neither Cloudflare nor allowed, and the whole stack
 * stops talking to itself.
 *
 * SSH is untouched: port 2222 arrives on INPUT, and nothing here is in INPUT.
 * The worst outcome is the site going dark with the box still reachable.
 */
function renderFirewall(v4: string[], v6: string[]): string {
  const rules = (ranges: string[], cmd: string) =>
    ranges.map((r) => `  ${cmd} -A KC-CF-ONLY -s ${r} -j RETURN`).join('\n')

  return `#!/usr/bin/env bash
# DO NOT EDIT. Generated by scripts/generate-cloudflare-ips.ts
#
# Allow 80/443 at the origin only from Cloudflare.
#
# Run this only after api.kerjacus.id and every other public hostname is
# proxied through Cloudflare. While a hostname is DNS-only its visitors reach
# the origin directly, and this script is precisely what stops that.
#
#   sudo bash infra/cloudflare-origin-firewall.sh apply
#   sudo bash infra/cloudflare-origin-firewall.sh revert
#
# Rules live in memory. Persist with netfilter-persistent once the site is
# confirmed healthy, never before - a reboot is the fastest way back.
set -euo pipefail

IFACE="\${KC_PUBLIC_IFACE:-eth0}"
PORTS="80,443"

apply() {
  for cmd in iptables ip6tables; do
    $cmd -N KC-CF-ONLY 2>/dev/null || $cmd -F KC-CF-ONLY
    # Replies to connections the origin itself opened.
    $cmd -A KC-CF-ONLY -m conntrack --ctstate RELATED,ESTABLISHED -j RETURN
  done

${rules(v4, 'iptables')}

${rules(v6, 'ip6tables')}

  for cmd in iptables ip6tables; do
    $cmd -A KC-CF-ONLY -j DROP
    # Idempotent: drop any previous hook before adding this one.
    while $cmd -D DOCKER-USER -i "$IFACE" -p tcp -m multiport --dports "$PORTS" -j KC-CF-ONLY 2>/dev/null; do :; done
    $cmd -I DOCKER-USER -i "$IFACE" -p tcp -m multiport --dports "$PORTS" -j KC-CF-ONLY
  done

  echo "Applied. Confirm the site is up, then persist with:"
  echo "  sudo netfilter-persistent save"
}

revert() {
  for cmd in iptables ip6tables; do
    while $cmd -D DOCKER-USER -i "$IFACE" -p tcp -m multiport --dports "$PORTS" -j KC-CF-ONLY 2>/dev/null; do :; done
    $cmd -F KC-CF-ONLY 2>/dev/null || true
    $cmd -X KC-CF-ONLY 2>/dev/null || true
  done
  echo "Reverted."
}

case "\${1:-}" in
  apply) apply ;;
  revert) revert ;;
  *) echo "usage: $0 apply|revert" >&2; exit 2 ;;
esac
`
}

async function main() {
  const check = process.argv.includes('--check')

  let ranges: string[]
  try {
    ranges = await fetchRanges()
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error)
    if (check) {
      console.log(`Could not reach Cloudflare (${reason}); skipping drift check.`)
      return
    }
    throw error
  }

  const v4 = ranges.filter((r) => r.includes('.'))
  const v6 = ranges.filter((r) => r.includes(':'))
  const outputs: [string, string][] = [
    [GATEWAY, renderGateway(ranges)],
    [FIREWALL, renderFirewall(v4, v6)],
  ]

  if (check) {
    const drifted = outputs.filter(([file, next]) => readFileSync(file, 'utf8') !== next)
    if (drifted.length === 0) {
      console.log(`Cloudflare ranges match (${ranges.length} ranges, ${outputs.length} files).`)
      return
    }
    console.error(
      `Drifted from what Cloudflare publishes: ${drifted.map(([f]) => path.basename(f)).join(', ')}\n` +
        'Run: bun run scripts/generate-cloudflare-ips.ts',
    )
    process.exit(1)
  }

  mkdirSync(path.dirname(FIREWALL), { recursive: true })
  for (const [file, next] of outputs) writeFileSync(file, next)
  console.log(`Wrote ${ranges.length} ranges to ${outputs.length} files`)
}

await main()
