// Code generated by apps/payment-service/scripts/generate-pricing.ts. DO NOT EDIT.
// Source of truth: packages/shared/src/pricing.ts

package pricing

// Bracket is one row of the platform fee table. A project fee at or below
// MaxFee splits at these rates; the platform's share rises with project size.
type Bracket struct {
	MaxFee      int64
	TalentShare float64
	FeeRate     float64
}

// Brackets is the published table, ordered by ascending MaxFee. The comparison
// is inclusive: a fee of exactly MaxFee belongs to that bracket.
var Brackets = []Bracket{
	{MaxFee: 3000000, TalentShare: 0.8725, FeeRate: 0.1275},
	{MaxFee: 5000000, TalentShare: 0.8225, FeeRate: 0.1775},
	{MaxFee: 10000000, TalentShare: 0.7725, FeeRate: 0.2275},
	{MaxFee: 15000000, TalentShare: 0.7225, FeeRate: 0.2775},
	{MaxFee: 20000000, TalentShare: 0.6725, FeeRate: 0.3275},
	{MaxFee: 30000000, TalentShare: 0.6225, FeeRate: 0.3775},
	{MaxFee: 50000000, TalentShare: 0.5725, FeeRate: 0.4275},
}

// TopShare applies above the last bracket's MaxFee.
var TopShare = struct {
	TalentShare float64
	FeeRate     float64
}{TalentShare: 0.5475, FeeRate: 0.4525}
