// Code generated by apps/payment-service/scripts/generate-pricing.ts. DO NOT EDIT.
// Source of truth: packages/shared/src/pricing.ts

package pricing

// Bracket is one row of the platform fee table. A project fee at or below
// MaxFee splits at these rates; the platform's share rises with project size.
type Bracket struct {
	MaxFee      int64
	TalentShare float64
	FeeRate     float64
}

// Brackets is the published table, ordered by ascending MaxFee. The comparison
// is inclusive: a fee of exactly MaxFee belongs to that bracket.
var Brackets = []Bracket{
	{MaxFee: 3000000, TalentShare: 0.815, FeeRate: 0.185},
	{MaxFee: 5000000, TalentShare: 0.765, FeeRate: 0.235},
	{MaxFee: 10000000, TalentShare: 0.715, FeeRate: 0.285},
	{MaxFee: 15000000, TalentShare: 0.665, FeeRate: 0.335},
	{MaxFee: 20000000, TalentShare: 0.615, FeeRate: 0.385},
	{MaxFee: 30000000, TalentShare: 0.565, FeeRate: 0.435},
	{MaxFee: 50000000, TalentShare: 0.515, FeeRate: 0.485},
}

// TopShare applies above the last bracket's MaxFee.
var TopShare = struct {
	TalentShare float64
	FeeRate     float64
}{TalentShare: 0.465, FeeRate: 0.535}
