// Code generated by apps/payment-service/scripts/generate-pricing.ts. DO NOT EDIT.
// Source of truth: packages/shared/src/pricing.ts

package pricing

// Bracket is one row of the platform fee table. A project fee at or below
// MaxFee splits at these rates; the platform's share rises with project size.
type Bracket struct {
	MaxFee      int64
	TalentShare float64
	FeeRate     float64
}

// Brackets is the published table, ordered by ascending MaxFee. The comparison
// is inclusive: a fee of exactly MaxFee belongs to that bracket.
var Brackets = []Bracket{
	{MaxFee: 3000000, TalentShare: 0.92, FeeRate: 0.08},
	{MaxFee: 5000000, TalentShare: 0.89, FeeRate: 0.11},
	{MaxFee: 10000000, TalentShare: 0.86, FeeRate: 0.14},
	{MaxFee: 15000000, TalentShare: 0.83, FeeRate: 0.17},
	{MaxFee: 20000000, TalentShare: 0.8, FeeRate: 0.2},
	{MaxFee: 30000000, TalentShare: 0.77, FeeRate: 0.23},
	{MaxFee: 50000000, TalentShare: 0.74, FeeRate: 0.26},
	{MaxFee: 100000000, TalentShare: 0.71, FeeRate: 0.29},
}

// TopShare applies above the last bracket's MaxFee.
var TopShare = struct {
	TalentShare float64
	FeeRate     float64
}{TalentShare: 0.68, FeeRate: 0.32}
